# 模型配置
model:
  type: "enhanced"  # 可选: "base" 或 "enhanced"
  hidden_dim: 128
  num_layers: 2
  num_heads: 8
  dropout: 0.1
  seq_length: 60
  
  # 增强版模型特有参数
  l1_lambda: 0.001
  l2_lambda: 0.001
  use_attention: true
  use_residual: true
  use_layer_norm: true

# 训练配置
training:
  num_epochs: 100
  batch_size: 32
  learning_rate: 0.001
  weight_decay: 0.0001
  early_stopping_patience: 10
  price_weight: 1.0
  volatility_weight: 0.5
  signal_weight: 1.0
  
  # 增强版训练特有参数
  extreme_event_weight: 0.3
  grad_clip_value: 1.0
  use_mixed_precision: true
  use_swa: true
  swa_start: 50
  use_ema: true
  ema_decay: 0.999
  use_adversarial: false
  adv_epsilon: 0.01

# 数据配置
data:
  cache_dir: "./data/cache"
  tickers: ["AAPL", "MSFT", "GOOGL"]
  start_date: "2018-01-01"
  end_date: "2023-01-01"
  interval: "1d"
  target_columns: ["Close"]
  feature_columns: ["Open", "High", "Low", "Close", "Volume"]
  use_enhanced_dataset: true
  add_technical_indicators: true
  add_time_features: true

# 数据集划分
splits:
  train:
    start_date: "2018-01-01"
    end_date: "2021-12-31"
  val:
    start_date: "2022-01-01"
    end_date: "2022-06-30"
  test:
    start_date: "2022-07-01"
    end_date: "2023-01-01"

# 不确定性估计配置
uncertainty:
  method: "mc_dropout"  
  dropout_rate: 0.2
  confidence_level: 0.95
